{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tinklink\/tinkerrorreason\/internalerror\/requestfailedfetchexistinguser"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/TinkLink\/documentation\/TinkLink","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/InternalError"]]},"abstract":[{"text":"The error can be caused by any of these things:","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/InternalError\/requestFailedFetchExistingUser"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"TinkLink"}],"title":"TinkErrorReason.InternalError.requestFailedFetchExistingUser","symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"s:8TinkLink0A11ErrorReasonO08InternalC0O30requestFailedFetchExistingUseryA2EmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestFailedFetchExistingUser"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestFailedFetchExistingUser","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"items":[{"content":[{"inlineContent":[{"code":"handoffSessionId","type":"codeVoice"},{"type":"text","text":" is missing."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"authorizationCode","type":"codeVoice"},{"type":"text","text":" is missing."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handoff session endpoint is unavailable."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The authentication\/token endpoint is unavailable.","type":"text"}]}]}],"type":"orderedList"}],"kind":"content"}],"references":{"doc://TinkLink/documentation/TinkLink/TinkErrorReason/InternalError/requestFailedFetchExistingUser":{"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/InternalError\/requestFailedFetchExistingUser","title":"TinkErrorReason.InternalError.requestFailedFetchExistingUser","abstract":[{"text":"The error can be caused by any of these things:","type":"text"}],"type":"topic","url":"\/documentation\/tinklink\/tinkerrorreason\/internalerror\/requestfailedfetchexistinguser","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"requestFailedFetchExistingUser","kind":"identifier"}]},"doc://TinkLink/documentation/TinkLink/TinkErrorReason/InternalError":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"InternalError","kind":"identifier"}],"navigatorTitle":[{"text":"InternalError","kind":"identifier"}],"title":"TinkErrorReason.InternalError","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/InternalError","role":"symbol","abstract":[{"text":"An unexpected internal error in Tinkâ€™s platform.","type":"text"}],"url":"\/documentation\/tinklink\/tinkerrorreason\/internalerror","type":"topic","kind":"symbol"},"doc://TinkLink/documentation/TinkLink":{"kind":"symbol","title":"TinkLink","type":"topic","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink","url":"\/documentation\/tinklink","role":"collection","abstract":[]},"doc://TinkLink/documentation/TinkLink/TinkErrorReason":{"type":"topic","kind":"symbol","title":"TinkErrorReason","url":"\/documentation\/tinklink\/tinkerrorreason","abstract":[{"text":"The error reason that describes the cause of the error.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TinkErrorReason"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TinkErrorReason"}],"role":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason"}}}