{"identifier":{"url":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus\/authenticationError(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/TinkLink\/documentation\/TinkLink","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus"]]},"abstract":[{"type":"text","text":"The error occurred during the authentication process with the bank."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"authenticationError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TinkErrorReason","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO"},{"text":".","kind":"text"},{"text":"AuthenticationErrorType","kind":"typeIdentifier","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/tinklink\/tinkerror\/errorstatus\/authenticationerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","metadata":{"title":"TinkError.ErrorStatus.authenticationError(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticationError"},{"text":"(","kind":"text"},{"text":"TinkErrorReason","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO","text":"AuthenticationErrorType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:8TinkLink0A5ErrorV0C6StatusO014authenticationC0yAeA0aC6ReasonO014AuthenticationC4TypeOcAEmF","modules":[{"name":"TinkLink"}],"roleHeading":"Case","symbolKind":"case","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://TinkLink/documentation/TinkLink/TinkErrorReason/AuthenticationErrorType":{"type":"topic","kind":"symbol","title":"TinkErrorReason.AuthenticationErrorType","url":"\/documentation\/tinklink\/tinkerrorreason\/authenticationerrortype","abstract":[{"text":"The error occurred during the authentication process with the bank.","type":"text"}],"navigatorTitle":[{"text":"AuthenticationErrorType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationErrorType"}],"role":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType"},"doc://TinkLink/documentation/TinkLink/TinkError":{"title":"TinkError","abstract":[{"type":"text","text":"An error returned by Tink service requests when something went wrong."}],"kind":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TinkError"}],"navigatorTitle":[{"text":"TinkError","kind":"identifier"}],"type":"topic","url":"\/documentation\/tinklink\/tinkerror"},"doc://TinkLink/documentation/TinkLink/TinkError/ErrorStatus/authenticationError(_:)":{"url":"\/documentation\/tinklink\/tinkerror\/errorstatus\/authenticationerror(_:)","kind":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus\/authenticationError(_:)","role":"symbol","type":"topic","abstract":[{"text":"The error occurred during the authentication process with the bank.","type":"text"}],"title":"TinkError.ErrorStatus.authenticationError(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticationError","kind":"identifier"},{"kind":"text","text":"("},{"text":"TinkErrorReason","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"AuthenticationErrorType","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO"},{"text":")","kind":"text"}]},"doc://TinkLink/documentation/TinkLink/TinkError/ErrorStatus":{"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus","navigatorTitle":[{"text":"ErrorStatus","kind":"identifier"}],"url":"\/documentation\/tinklink\/tinkerror\/errorstatus","type":"topic","abstract":[{"text":"The error status describes the category for the error that occurred.","type":"text"}],"kind":"symbol","title":"TinkError.ErrorStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorStatus","kind":"identifier"}],"role":"symbol"},"doc://TinkLink/documentation/TinkLink":{"kind":"symbol","title":"TinkLink","type":"topic","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink","url":"\/documentation\/tinklink","role":"collection","abstract":[]},"doc://TinkLink/documentation/TinkLink/TinkErrorReason":{"type":"topic","kind":"symbol","title":"TinkErrorReason","url":"\/documentation\/tinklink\/tinkerrorreason","abstract":[{"text":"The error reason that describes the cause of the error.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TinkErrorReason"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TinkErrorReason"}],"role":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason"}}}